#!/usr/bin/env python3

"""AI Hub governance hook projection: gemini-beforeagent."""
import json
import sys

payload = json.load(sys.stdin)
if not isinstance(payload, dict):
    msg = "hook input must be a JSON object"
    raise TypeError(msg)
response = json.loads(
    ('{"hookSpecificOutput":{"hookEventName":"BeforeAgent","additional'
         'Context":"<!-- AIHUB-GOVERNANCE-CAPSULE v1 sha256:e1b7a9ae088643'
         'bf660b78ff1aea55d49076ec46518707976d77c78ed23db5db -->\\n# Gener'
         'ated session governance capsule\\n\\nThis projection is derived '
         'by `agentsctl sync`; edit canonical `AGENTS.md`, `rules/`, `skil'
         'ls/`, or `commands/`, never this output. The operator\'s newest '
         'request has precedence. Provider hooks are delivery mechanisms, '
         'not policy owners.\\n\\n## Rule `architecture/engineering-core`\\'
         'n\\n# Engineering core\\n\\nFor every implementation:\\n\\n1. Re'
         'search repository owners, dependencies, and canonical documentat'
         'ion.\\n2. Remove scope without a current requirement or consumer'
         ' (YAGNI).\\n3. Elect one writable authority; every other copy is'
         ' a generated projection\\n   (SSOT).\\n4. Apply SOLID only to a '
         'responsibility or dependency boundary under change.\\n5. Impleme'
         'nt through the owner and simplify without weakening behavior.\\n'
         '6. Remove duplication and god components; recheck YAGNI, SSOT, S'
         'OLID.\\n7. Exercise runtime behavior, run every applicable nativ'
         'e gate, and complete\\n   the approved landing cycle before chan'
         'ging phase.\\n\\nAt a cross-boundary failure, prove the producer'
         ' contract and output. Fix its\\nowner when invalid or the receiv'
         'er when it conforms. Never alter a correct\\nadjacent owner for '
         'an invalid consumer; symptom workarounds are defects.\\n\\nHardc'
         'odes, normalized failure, failover, retry, fallback, compatibili'
         'ty,\\npartial execution, keyring, and unevidenced success are de'
         'fects. Typed owners\\nkeep defaults. The first exception escapes'
         ' its CLI with traceback and cause.\\n\\nGit, runtime, build, and'
         ' tests are baseline. Auxiliary tracking is a capability.\\nAuxil'
         'iary capabilities apply only when authorized and selected; insta'
         'llation\\nnever selects. Do not load, probe, or gate dormant cap'
         'abilities. Invalid\\nselected authorization, configuration, read'
         'iness, or result fails without\\nfallback. Require only non-deri'
         'vable values.\\n\\nAn external token validation without its toke'
         'n is not executed and is recorded\\nas `NOT EXECUTED`, never gre'
         'en; it does not block offline gates, landing, or\\npost-merge pr'
         'oof. Direct invocation selects it: the token becomes required an'
         'd\\nany failure escapes without skip, catch, fallback, or normal'
         'ization.\\n\\nCompose with generalized ownership,\\nstrict execu'
         'tion,\\nruntime evidence,\\nstorage isolation,\\nsecurity closur'
         'e.\\n\\n## Rule `coordination/fix-forward-collaboration`\\n\\n# '
         'Adopt the current state and collaborate by fix-forward\\n\\nTrea'
         't every current authorized-repository change as owned input rega'
         'rdless of\\nprovenance or age. Re-read shared files, attribute o'
         'verlapping intent, preserve\\ncompatible contributions, and adop'
         't them through the integration lane. The\\ncombined result is th'
         'e target; provenance never exempts a defect from fix-forward.\\n'
         '\\nPreserve unmanifested provider output, generated destinations'
         ', external files,\\nand ambiguous objects without promoting them'
         ' to canonical input. Bulk adoption\\nor replacement requires div'
         'ergent-object adjudication.\\n\\nNever stash, reset, restore, re'
         'vert, rebase, force-push, roll back code/history,\\nor replace s'
         'hared files to remove work. Fix the canonical owner forward.\\nT'
         'ransaction rollback may undo only its failing invocation\'s effe'
         'cts.\\n\\nA severe conflict exists only when two current intenti'
         'ons require incompatible\\nbehavior or when preserving both woul'
         'd violate a higher authority. Stop before\\nthe conflicting effe'
         'ct, present both intentions and their evidence, and ask the\\nop'
         'erator one precise question. Ordinary overlap, divergence, a red'
         ' gate, or\\nintegration work is not severe: reconcile, validate,'
         ' and continue forward.\\nUnexpected state requires fresh preflig'
         'ht; it proves no actor or intention and\\nnever authorizes an un'
         'changed retry.\\n\\nCompose this invariant with shared-file coor'
         'dination,\\noperator precedence,\\nplan adoption, and\\nthe dest'
         'ructive Git guard.\\n\\n## Rule `coordination/operator-precedenc'
         'e`\\n\\n# Newest operator instruction wins; adjust artifacts to '
         'it\\n\\nAuthority order: operator request > declared orchestrati'
         'on contract > canonical\\ntracker > ADRs > skills > docs, and ne'
         'west supersedes oldest. On conflict,\\nadjust the lower or older'
         ' artifact to match; never override the operator to\\nsatisfy sta'
         'le guidance.\\n\\nWhile orchestration and tracker runtimes are s'
         'uspended, do not invoke them.\\nCreate no substitute tracker or '
         'ledger, preserve implementation evidence only\\nin separately au'
         'thorized Git/PR/CI, and leave phase closure open.\\n\\nExact ope'
         'rator authorization naming targets, disposition, recovery, and\\'
         'nvalidation survives interruption, divergence, and red gates; re'
         '-preflight and\\ncontinue. Ask only when the effect expands beyo'
         'nd it or two evidenced current\\nintentions conflict. State alon'
         'e proves no intention, actor, or process.\\n\\n## Rule `coordina'
         'tion/session-governance`\\n\\n# Rehydrate governance at every ag'
         'ent context boundary\\n\\nStatic provider instructions own the c'
         'omplete standing contract. Provider hooks\\nrefresh a compact go'
         'vernance capsule at every native equivalent of session\\nstart, '
         'prompt submission, context compaction, and subagent start. A hoo'
         'k is a\\ndelivery mechanism generated by optionless `agentsctl s'
         'ync`; it is never a\\npolicy owner, public command, fallback, da'
         'emon, or second runtime path.\\n\\nAt session start, load the cu'
         'rrent operator and repository instructions before\\nwork. At eac'
         'h prompt, apply the newest operator intent and route only the sk'
         'ills\\nmaterial to that request. After compaction, restore the a'
         'ctive goal, evidence,\\nscope, exclusions, accepted concurrent w'
         'ork, first red gate, and next action.\\nEvery subagent inherits '
         'the current authority, fix-forward contract, and a\\nbounded ass'
         'ignment; it may not discard, stash, roll back, or overwrite anot'
         'her\\nactor\'s work.\\n\\nProvider capability is explicit in `co'
         'nfig/projections.json`. An exact native\\nevent is used when ava'
         'ilable. A documented per-turn or pre-model equivalent is\\nused '
         'when it is the provider\'s only delivery point, and observationa'
         'l events\\nremain observational. Never claim an exact lifecycle '
         'semantic that the provider\\ndoes not expose. Declarative instru'
         'ctions and projected skills/rules remain the\\nstanding guarante'
         'e when a hook can only observe or advise.\\n\\nCompose with oper'
         'ator precedence,\\nfix-forward collaboration,\\nstrict execution'
         ', and\\nruntime evidence.\\n\\n## Rule `ethics/professional-inte'
         'grity`\\n\\n# Professional integrity is absolute\\n\\nNever lie,'
         ' fabricate evidence, hide a blocker, bypass a gate, or patch a s'
         'ymptom\\nonly to make a check pass. Fix the generalized root cau'
         'se with full context and\\nreport exact command, working directo'
         'ry, exit code and decisive output.\\n\\n## Rule `runtime/strict-'
         'execution`\\n\\n# Strict execution is universal and non-optional'
         '\\n\\nEvery project and projected agent applies all of these pol'
         'icies together:\\n\\n- fail loud;\\n- no fallback;\\n- preflight'
         ' before effects;\\n- required environment;\\n- atomic effects;\\'
         'n- causal subprocess propagation;\\n- no keyring;\\n- zero resid'
         'ue.\\n\\nThe policies are cumulative. A project rule may make th'
         'em narrower or reject\\nmore inputs; it cannot relax, catch, nor'
         'malize, skip, defer, or route around any\\nof them. Existing opp'
         'osing behavior is a blocking violation to exterminate at\\nits o'
         'wner, never grandfathered compatibility.\\n\\nResolve gate appli'
         'cability before invocation. A dormant external-token gate is\\nn'
         'ot executed; selecting or invoking it applies every policy above'
         '.\\n\\n## Rule `workflow/canonical-commands`\\n\\n# Run agent fu'
         'nctions only through the optionless CLI\\n\\n`agentsctl` is the '
         'sole agent-runtime facade: `help`, `doctor`, `check`, `sync`,\\n'
         '`evaluate`, `secure`, `clean`, and `live`. Each invocation has e'
         'xactly one verb\\nand no option, argument, mode, selector, alias'
         ', or compatibility syntax.\\n\\nMake is development support and '
         'gate composition. A Make target that needs\\nruntime behavior in'
         'vokes one public `agentsctl` verb; it never imports a private\\n'
         'runtime function, reconstructs orchestration, or creates a secon'
         'd API.\\n\\nAd hoc shell, inline Python, diagnostics, and test h'
         'elpers used as operational\\nsubstitutes never import or execute'
         ' private agent runtime. Repository and GitHub\\nwork uses its de'
         'clared `make`, `git`, and `gh` owner, never an executable\\nlowe'
         'r-level substitute.\\n\\nA broken or out-of-pattern command is a'
         ' defect to fix at its owner and rerun\\nthrough the same surface'
         '. Bypasses are blocking violations, not warnings.\\n\\n## Rule `'
         'workflow/runtime-is-reality`\\n\\n# Reality is the running syste'
         'm; tests are checks, not the SSOT\\n\\nValidate against the real'
         ' declared runtime (CLI, daemon, config, or public API)\\nand exe'
         'rcise the actual feature—type and lint green are necessary, not\\'
         'nsufficient.\\n\\n- A test that only passes by keeping removed o'
         'r legacy artifacts is wrong: fix or\\n  delete the test; never r'
         'estore legacy just to make it pass.\\n- A config/settings test t'
         'hat breaks when a valid SSOT value changes is defective.\\n  Tes'
         't contracts and derivations across arbitrary valid inputs; golde'
         'ns may lock\\n  generated structure, never mutable config-owned '
         'values.\\n- A missing facade constant fails only at runtime — im'
         'port and run the real path.\\n- Before concluding root cause, pr'
         'ove the running or installed artifact matches\\n  the declared a'
         'uthoritative revision or release. An editable checkout, local\\n'
         '  cache, generated copy, or stale environment is not evidence of'
         ' remote/runtime\\n  behavior until identity is verified.\\n- Use'
         ' the newest released version of every required tool. Every diagn'
         'ostic it\\n  emits is blocking. A cap, downgrade, substitution, '
         'suppression, compatibility\\n  classification, or false-positive'
         ' classification requires prior operator\\n  discussion, reproduc'
         'ible evidence, and explicit authorization; without all\\n  three'
         ', correct the owner and rerun that released version.\\n\\n## Cap'
         'ability indexes\\n\\nSkills: caveman, context-canary, fix-forwar'
         'd-collaboration, governance-audit, operator-correction-learning,'
         ' plan-focus-recovery, sprint-closure, strategic-compact, verific'
         'ation-loop\\nCommands: add-language-rules, database-migration, f'
         'eature-development, ghi-list, pr-list, ralph-loop, security-tria'
         'ge, synthesize-governance\\n"}}'),

)
json.dump(response, sys.stdout, ensure_ascii=False, separators=(",", ":"))
sys.stdout.write("\n")
