#!/usr/bin/env python3

"""AI Hub governance hook projection: codex-subagentstart."""
import json
import sys

payload = json.load(sys.stdin)
if not isinstance(payload, dict):
    msg = "hook input must be a JSON object"
    raise TypeError(msg)
response = json.loads(
    ('{"hookSpecificOutput":{"hookEventName":"SubagentStart","addition'
         'alContext":"<!-- AIHUB-GOVERNANCE-CAPSULE v1 sha256:e1b7a9ae0886'
         '43bf660b78ff1aea55d49076ec46518707976d77c78ed23db5db -->\\n# Gen'
         'erated session governance capsule\\n\\nThis projection is derive'
         'd by `agentsctl sync`; edit canonical `AGENTS.md`, `rules/`, `sk'
         'ills/`, or `commands/`, never this output. The operator\'s newes'
         't request has precedence. Provider hooks are delivery mechanisms'
         ', not policy owners.\\n\\n## Rule `architecture/engineering-core'
         '`\\n\\n# Engineering core\\n\\nFor every implementation:\\n\\n1.'
         ' Research repository owners, dependencies, and canonical documen'
         'tation.\\n2. Remove scope without a current requirement or consu'
         'mer (YAGNI).\\n3. Elect one writable authority; every other copy'
         ' is a generated projection\\n   (SSOT).\\n4. Apply SOLID only to'
         ' a responsibility or dependency boundary under change.\\n5. Impl'
         'ement through the owner and simplify without weakening behavior.'
         '\\n6. Remove duplication and god components; recheck YAGNI, SSOT'
         ', SOLID.\\n7. Exercise runtime behavior, run every applicable na'
         'tive gate, and complete\\n   the approved landing cycle before c'
         'hanging phase.\\n\\nAt a cross-boundary failure, prove the produ'
         'cer contract and output. Fix its\\nowner when invalid or the rec'
         'eiver when it conforms. Never alter a correct\\nadjacent owner f'
         'or an invalid consumer; symptom workarounds are defects.\\n\\nHa'
         'rdcodes, normalized failure, failover, retry, fallback, compatib'
         'ility,\\npartial execution, keyring, and unevidenced success are'
         ' defects. Typed owners\\nkeep defaults. The first exception esca'
         'pes its CLI with traceback and cause.\\n\\nGit, runtime, build, '
         'and tests are baseline. Auxiliary tracking is a capability.\\nAu'
         'xiliary capabilities apply only when authorized and selected; in'
         'stallation\\nnever selects. Do not load, probe, or gate dormant '
         'capabilities. Invalid\\nselected authorization, configuration, r'
         'eadiness, or result fails without\\nfallback. Require only non-d'
         'erivable values.\\n\\nAn external token validation without its t'
         'oken is not executed and is recorded\\nas `NOT EXECUTED`, never '
         'green; it does not block offline gates, landing, or\\npost-merge'
         ' proof. Direct invocation selects it: the token becomes required'
         ' and\\nany failure escapes without skip, catch, fallback, or nor'
         'malization.\\n\\nCompose with generalized ownership,\\nstrict ex'
         'ecution,\\nruntime evidence,\\nstorage isolation,\\nsecurity clo'
         'sure.\\n\\n## Rule `coordination/fix-forward-collaboration`\\n\\'
         'n# Adopt the current state and collaborate by fix-forward\\n\\nT'
         'reat every current authorized-repository change as owned input r'
         'egardless of\\nprovenance or age. Re-read shared files, attribut'
         'e overlapping intent, preserve\\ncompatible contributions, and a'
         'dopt them through the integration lane. The\\ncombined result is'
         ' the target; provenance never exempts a defect from fix-forward.'
         '\\n\\nPreserve unmanifested provider output, generated destinati'
         'ons, external files,\\nand ambiguous objects without promoting t'
         'hem to canonical input. Bulk adoption\\nor replacement requires '
         'divergent-object adjudication.\\n\\nNever stash, reset, restore,'
         ' revert, rebase, force-push, roll back code/history,\\nor replac'
         'e shared files to remove work. Fix the canonical owner forward.\\'
         'nTransaction rollback may undo only its failing invocation\'s ef'
         'fects.\\n\\nA severe conflict exists only when two current inten'
         'tions require incompatible\\nbehavior or when preserving both wo'
         'uld violate a higher authority. Stop before\\nthe conflicting ef'
         'fect, present both intentions and their evidence, and ask the\\n'
         'operator one precise question. Ordinary overlap, divergence, a r'
         'ed gate, or\\nintegration work is not severe: reconcile, validat'
         'e, and continue forward.\\nUnexpected state requires fresh prefl'
         'ight; it proves no actor or intention and\\nnever authorizes an '
         'unchanged retry.\\n\\nCompose this invariant with shared-file co'
         'ordination,\\noperator precedence,\\nplan adoption, and\\nthe de'
         'structive Git guard.\\n\\n## Rule `coordination/operator-precede'
         'nce`\\n\\n# Newest operator instruction wins; adjust artifacts t'
         'o it\\n\\nAuthority order: operator request > declared orchestra'
         'tion contract > canonical\\ntracker > ADRs > skills > docs, and '
         'newest supersedes oldest. On conflict,\\nadjust the lower or old'
         'er artifact to match; never override the operator to\\nsatisfy s'
         'tale guidance.\\n\\nWhile orchestration and tracker runtimes are'
         ' suspended, do not invoke them.\\nCreate no substitute tracker o'
         'r ledger, preserve implementation evidence only\\nin separately '
         'authorized Git/PR/CI, and leave phase closure open.\\n\\nExact o'
         'perator authorization naming targets, disposition, recovery, and'
         '\\nvalidation survives interruption, divergence, and red gates; '
         're-preflight and\\ncontinue. Ask only when the effect expands be'
         'yond it or two evidenced current\\nintentions conflict. State al'
         'one proves no intention, actor, or process.\\n\\n## Rule `coordi'
         'nation/session-governance`\\n\\n# Rehydrate governance at every '
         'agent context boundary\\n\\nStatic provider instructions own the'
         ' complete standing contract. Provider hooks\\nrefresh a compact '
         'governance capsule at every native equivalent of session\\nstart'
         ', prompt submission, context compaction, and subagent start. A h'
         'ook is a\\ndelivery mechanism generated by optionless `agentsctl'
         ' sync`; it is never a\\npolicy owner, public command, fallback, '
         'daemon, or second runtime path.\\n\\nAt session start, load the '
         'current operator and repository instructions before\\nwork. At e'
         'ach prompt, apply the newest operator intent and route only the '
         'skills\\nmaterial to that request. After compaction, restore the'
         ' active goal, evidence,\\nscope, exclusions, accepted concurrent'
         ' work, first red gate, and next action.\\nEvery subagent inherit'
         's the current authority, fix-forward contract, and a\\nbounded a'
         'ssignment; it may not discard, stash, roll back, or overwrite an'
         'other\\nactor\'s work.\\n\\nProvider capability is explicit in `'
         'config/projections.json`. An exact native\\nevent is used when a'
         'vailable. A documented per-turn or pre-model equivalent is\\nuse'
         'd when it is the provider\'s only delivery point, and observatio'
         'nal events\\nremain observational. Never claim an exact lifecycl'
         'e semantic that the provider\\ndoes not expose. Declarative inst'
         'ructions and projected skills/rules remain the\\nstanding guaran'
         'tee when a hook can only observe or advise.\\n\\nCompose with op'
         'erator precedence,\\nfix-forward collaboration,\\nstrict executi'
         'on, and\\nruntime evidence.\\n\\n## Rule `ethics/professional-in'
         'tegrity`\\n\\n# Professional integrity is absolute\\n\\nNever li'
         'e, fabricate evidence, hide a blocker, bypass a gate, or patch a'
         ' symptom\\nonly to make a check pass. Fix the generalized root c'
         'ause with full context and\\nreport exact command, working direc'
         'tory, exit code and decisive output.\\n\\n## Rule `runtime/stric'
         't-execution`\\n\\n# Strict execution is universal and non-option'
         'al\\n\\nEvery project and projected agent applies all of these p'
         'olicies together:\\n\\n- fail loud;\\n- no fallback;\\n- preflig'
         'ht before effects;\\n- required environment;\\n- atomic effects;'
         '\\n- causal subprocess propagation;\\n- no keyring;\\n- zero res'
         'idue.\\n\\nThe policies are cumulative. A project rule may make '
         'them narrower or reject\\nmore inputs; it cannot relax, catch, n'
         'ormalize, skip, defer, or route around any\\nof them. Existing o'
         'pposing behavior is a blocking violation to exterminate at\\nits'
         ' owner, never grandfathered compatibility.\\n\\nResolve gate app'
         'licability before invocation. A dormant external-token gate is\\'
         'nnot executed; selecting or invoking it applies every policy abo'
         've.\\n\\n## Rule `workflow/canonical-commands`\\n\\n# Run agent '
         'functions only through the optionless CLI\\n\\n`agentsctl` is th'
         'e sole agent-runtime facade: `help`, `doctor`, `check`, `sync`,\\'
         'n`evaluate`, `secure`, `clean`, and `live`. Each invocation has '
         'exactly one verb\\nand no option, argument, mode, selector, alia'
         's, or compatibility syntax.\\n\\nMake is development support and'
         ' gate composition. A Make target that needs\\nruntime behavior i'
         'nvokes one public `agentsctl` verb; it never imports a private\\'
         'nruntime function, reconstructs orchestration, or creates a seco'
         'nd API.\\n\\nAd hoc shell, inline Python, diagnostics, and test '
         'helpers used as operational\\nsubstitutes never import or execut'
         'e private agent runtime. Repository and GitHub\\nwork uses its d'
         'eclared `make`, `git`, and `gh` owner, never an executable\\nlow'
         'er-level substitute.\\n\\nA broken or out-of-pattern command is '
         'a defect to fix at its owner and rerun\\nthrough the same surfac'
         'e. Bypasses are blocking violations, not warnings.\\n\\n## Rule '
         '`workflow/runtime-is-reality`\\n\\n# Reality is the running syst'
         'em; tests are checks, not the SSOT\\n\\nValidate against the rea'
         'l declared runtime (CLI, daemon, config, or public API)\\nand ex'
         'ercise the actual feature—type and lint green are necessary, not'
         '\\nsufficient.\\n\\n- A test that only passes by keeping removed'
         ' or legacy artifacts is wrong: fix or\\n  delete the test; never'
         ' restore legacy just to make it pass.\\n- A config/settings test'
         ' that breaks when a valid SSOT value changes is defective.\\n  T'
         'est contracts and derivations across arbitrary valid inputs; gol'
         'dens may lock\\n  generated structure, never mutable config-owne'
         'd values.\\n- A missing facade constant fails only at runtime — '
         'import and run the real path.\\n- Before concluding root cause, '
         'prove the running or installed artifact matches\\n  the declared'
         ' authoritative revision or release. An editable checkout, local\\'
         'n  cache, generated copy, or stale environment is not evidence o'
         'f remote/runtime\\n  behavior until identity is verified.\\n- Us'
         'e the newest released version of every required tool. Every diag'
         'nostic it\\n  emits is blocking. A cap, downgrade, substitution,'
         ' suppression, compatibility\\n  classification, or false-positiv'
         'e classification requires prior operator\\n  discussion, reprodu'
         'cible evidence, and explicit authorization; without all\\n  thre'
         'e, correct the owner and rerun that released version.\\n\\n## Ca'
         'pability indexes\\n\\nSkills: caveman, context-canary, fix-forwa'
         'rd-collaboration, governance-audit, operator-correction-learning'
         ', plan-focus-recovery, sprint-closure, strategic-compact, verifi'
         'cation-loop\\nCommands: add-language-rules, database-migration, '
         'feature-development, ghi-list, pr-list, ralph-loop, security-tri'
         'age, synthesize-governance\\n"}}'),

)
json.dump(response, sys.stdout, ensure_ascii=False, separators=(",", ":"))
sys.stdout.write("\n")
