from collections.abc import Generator
from typing import Any

import pytest

def oracle_shared_container_environment() -> None: ...
def set_test_environment() -> Generator[None]: ...
@pytest.fixture
def dbt_oracle_profile() -> dict[str, object]: ...
@pytest.fixture
def dbt_project_config() -> dict[str, object]: ...
@pytest.fixture
def oracle_adapter_config() -> dict[str, object]: ...
@pytest.fixture
def dbt_model_definitions() -> dict[str, str]: ...
@pytest.fixture
def dbt_macro_definitions() -> dict[str, str]: ...
@pytest.fixture
def dbt_test_definitions() -> dict[str, str]: ...
@pytest.fixture
def dbt_source_definitions() -> dict[str, object]: ...
@pytest.fixture
def oracle_sql_queries() -> dict[str, str]: ...
@pytest.fixture
def dbt_run_config() -> dict[str, object]: ...
@pytest.fixture
def dbt_test_config() -> dict[str, object]: ...
@pytest.fixture
def performance_test_config() -> dict[str, object]: ...
@pytest.fixture
def dbt_error_scenarios() -> list[dict[str, object]]: ...
def pytest_configure(config: pytest.Config) -> None: ...

class MockConnectionManager:
    connections: dict[str, object]
    def __init__(self) -> None: ...
    def open_connection(
        self, name: str, config: dict[str, object]
    ) -> dict[str, object]: ...
    def close_connection(self, name: str) -> None: ...

class MockSqlExecutor:
    def execute(
        self, sql: str, *, auto_begin: bool = True
    ) -> tuple[str, list[Any]]: ...

class MockModelCompiler:
    def compile_model(self, model_sql: str, context: dict[str, object]) -> str: ...

class MockRelationManager:
    def get_relation(
        self, database: str, schema: str, identifier: str
    ) -> dict[str, str]: ...
    def list_relations_without_caching(self, schema: str) -> list[dict[str, str]]: ...

@pytest.fixture
def mock_dbt_oracle_adapter() -> object: ...
@pytest.fixture
def mock_dbt_runner() -> object: ...
