from unittest.mock import Mock

class TestOracleCredentials:
    def test_oracle_credentials_creation(self) -> None: ...
    def test_connection_keys(self) -> None: ...
    def test_database_identifier(self) -> None: ...
    def test_to_oracle_config(self) -> None: ...

class TestConnectionManager:
    def test_connection_manager_init(self) -> None: ...
    def test_open_connection_success(
        self,
        mock_query_service: Mock,
        mock_connection_service: Mock,
        mock_async_run: Mock,
    ) -> None: ...
    def test_handle_connection_error(self) -> None: ...
    def test_cancel_open_connections(self) -> None: ...

class TestAsyncHelpers:
    def test_run_async_in_sync_context(self) -> None: ...
    def test_run_async_in_sync_context_with_exception(self) -> None: ...

class TestExecuteQueries:
    def test_execute_query_success(self, mock_async_run: Mock) -> None: ...

class TestFallbackCursor:
    def test_add_query_with_fallback_cursor(self) -> None: ...

class TestTransactionMethods:
    def test_begin_transaction(self) -> None: ...
    def test_commit_transaction(self) -> None: ...
    def test_rollback_transaction(self) -> None: ...
