class TestOracleAdapter:
    def test_adapter_creation(self) -> None: ...
    def test_adapter_type(self) -> None: ...
    def test_date_function(self) -> None: ...
    def test_is_cancelable(self) -> None: ...
    def test_get_columns_in_relation(self) -> None: ...
    def test_list_relations_without_caching(self) -> None: ...
    def test_check_schema_exists(self) -> None: ...
    def test_check_schema_not_exists(self) -> None: ...
    def test_create_schema(self) -> None: ...
    def test_drop_schema(self) -> None: ...
    def test_get_catalog(self) -> None: ...
    def test_convert_text_type(self) -> None: ...
    def test_convert_number_type(self) -> None: ...
    def test_convert_datetime_type(self) -> None: ...
    def test_adapter_inheritance(self) -> None: ...
    def test_adapter_with_real_connection_manager(self) -> None: ...
    def test_relation_handling(self) -> None: ...
    def test_sql_generation_methods(self) -> None: ...
    def test_oracle_specific_features(self) -> None: ...
    def test_adapter_error_handling(self) -> None: ...

class TestAdapterIntegration:
    def test_adapter_connection_manager_integration(self) -> None: ...
    def test_adapter_with_mock_connection(self) -> None: ...

class TestAdapterConfiguration:
    def test_adapter_accepts_various_config_formats(self) -> None: ...
    def test_adapter_with_minimal_config(self) -> None: ...
