class TestDBTOracleConfig:
    def test_basic_config_creation(self) -> None: ...
    def test_config_with_sid(self) -> None: ...
    def test_config_validation_missing_host(self) -> None: ...
    def test_config_validation_missing_username(self) -> None: ...
    def test_config_validation_missing_password(self) -> None: ...
    def test_config_validation_invalid_materialization(self) -> None: ...
    def test_config_validation_invalid_protocol(self) -> None: ...
    def test_config_validation_pool_sizes(self) -> None: ...
    def test_get_connection_string(self) -> None: ...
    def test_get_connection_string_with_sid(self) -> None: ...
    def test_get_effective_schema(self) -> None: ...
    def test_get_database_identifier(self) -> None: ...
    def test_to_connection_config(self) -> None: ...
    def test_to_oracle_config(self) -> None: ...
    def test_get_performance_settings(self) -> None: ...
    def test_get_dbt_settings(self) -> None: ...

class TestDBTOracleSettings:
    def test_settings_creation(self) -> None: ...
    def test_settings_from_environment(self) -> None: ...
    def test_to_dbt_config(self) -> None: ...

class TestConfigEdgeCases:
    def test_config_with_all_optional_fields(self) -> None: ...
    def test_config_defaults_when_no_service_name_or_sid(self) -> None: ...
    def test_config_field_validation_ranges(self) -> None: ...
    def test_config_materialization_validation_all_valid_types(self) -> None: ...
    def test_config_protocol_validation_all_valid_types(self) -> None: ...

class TestConfigConstantsUsage:
    def test_config_uses_default_constants(self) -> None: ...
